# 6000 Dice Game Configuration
game:
  human_player_name: "Human"
  computer_player_name: "Computer"
  computer_strategy: "adaptive" # Options: "conservative", "balanced", "aggressive", "adaptive"
  ai_output_language: "fr" # fr, en
  ai_personality: "default" # Options: "default", "paranoid", "academic", "vicious"

server:
  host: "0.0.0.0"
  port: 3000

openai:
  url: "https://api.openai.com/v1/chat/completions"
  model: "gpt-4"

anthropic:
  url: "https://api.anthropic.com/v1/messages"
  model: "claude-opus-4-20250514"

ollama:
  enabled: true
  url: "http://localhost:11434/api/generate"
  model: "llama3:latest"
  timeout: 120